version: '3.9'

services:
  web:
    build: .
    working_dir: /code/app
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./app:/code/app
    ports:
      - 8080:8080